### ISSUE TITLE
[FEAT] 메인 페이지 수정

### ISSUE THREAD

**Issue by nicehcy2** [WE-SAVE-UMC/BE#119]
## Description 
- 프론트와 연동을 하는 과정에서 메인페이지 API에서 몇 가지 수정 사항을 알게 되었습니다.

## TODO 
- [x] 국내 사건사고 DTO에 카테고리 추가
- [x] 거리, 시간 데이터 format 맞추기
- [x] 이미지 데이터 넘겨주기
