### ISSUE TITLE
[FEAT] 메인 페이지 API 추가 구현

### ISSUE THREAD

**Issue by nicehcy2** [WE-SAVE-UMC/BE#51]
## Description 
메인 페이지 확인순, 거리순 API를 구현합니다.
메인 페이지 검색 기능을 구현합니다.

## TODO 
- [ ] 내 근처 사건, 사고 확인순 구현
- [ ] 내 근처 사건, 사고 조회순 구현
- [ ] 메인 페이지 검색 기능 구현

## ETC 
기타 사항
